import globals from 'globals';
import pluginJs from '@eslint/js';
import tseslint from 'typescript-eslint';


export default [
    { files: ['**/*.{js,mjs,cjs,ts}'] },
    { languageOptions: { globals: globals.browser } },
    {
        rules: {
            'no-console': 'warn',
            'no-undef': 'error',
            'no-unused-vars': 'error',
            'no-duplicate-imports': 'error',
            'no-unreachable': 'error',
            'no-useless-assignment': 'error',
            'block-scoped-var': 'error',
            'camelcase': 'error',
            'consistent-return': 'error',
            'default-case': 'error',
            'default-case-last': 'error',
            'default-param-last': 'error',
            'dot-notation': 'error',
            'eqeqeq': 'error',
            'no-else-return': 'error',
            'no-empty': 'error',
            'no-empty-function': 'error',
            'no-lone-blocks': 'error',
            'no-multi-spaces': 'error',
            'no-multi-str': 'error',
            'no-magic-numbers': 'error',
            'no-lonely-if': 'error',
            'no-loop-func': 'error',
            'no-undef-init': 'error',
            'no-unneeded-ternary': 'error',
            'no-unused-expressions': 'error',
            'no-useless-return': 'error',
            'no-useless-concat': 'error',
            'no-useless-catch': 'error',
            'no-useless-escape': 'error',
            'no-useless-rename': 'error',
            'no-var': 'error',
            'no-void': 'error',
            'prefer-const': 'error',
            'prefer-arrow-callback': 'error',
            'prefer-template': 'error',
            'require-await': 'error',
            'sort-imports': 'error',
            'sort-vars': 'error',
            'sort-keys': 'error',
        },
    },
    pluginJs.configs.recommended,
    ...tseslint.configs.recommended,
];